apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service-deploy
  namespace: fintech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet-service
  template:
    metadata:
      labels:
        app: wallet-service
    spec:
      containers:
        - name: wallet-service
          image: public.ecr.aws/z1z0w2y6/wallet-service:latest
          ports:
            - containerPort: 8099
          envFrom:
            - configMapRef:
                name: wallet-service-config
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "default"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8099
            initialDelaySeconds: 30
            periodSeconds: 10
