apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: fintech
type: Opaque
stringData:
  username: "postgres"
  password: "password"
  url: "jdbc:postgresql://postgres-instance.c122egeymo28.us-east-1.rds.amazonaws.com:5432/wallet_service_db"